apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-api
  labels:
    app: shop-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop-api
  template:
    metadata:
      labels:
        app: shop-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: shop-api-container
        image: paulbouwer/hello-kubernetes:1.7
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 1
          failureThreshold: 2

---
apiVersion: v1
kind: Service
metadata:
  name: probe-metrics-svc
  labels:
    app: shop-api
spec:
  type: NodePort
  selector:
    app: shop-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
